#!/bin/sh
# unix2dos,v 1.202 2001/04/27 09:58:36 rleyton Exp
# Converts the files in the current directory to DOS files, ie. with a 
# CR/LF combination, rather than the standard LF in Unix.

file=$1
cat $file | sed 's/$//g' > /tmp/ril
mv -f /tmp/ril $file
